package main

import (
	"fmt"
	"io"
	"os"

	"github.com/paranpen/yangc/pkg/yang"
	"github.com/spf13/cobra"
)

func init() {
	var headerCmd = &cobra.Command{
		Use:   ".",
		Short: "yangc to generate C header files",
		Run: func(cmd *cobra.Command, args []string) {
			entries := doCompile(yangFileName)
			doHeader(os.Stdout, entries)
		},
	}
	mainCmd.AddCommand(headerCmd)
}

func doHeader(w io.Writer, entries []*yang.Entry) {
	// PrintNode
	for _, e := range entries {
		yang.PrintNode(w, e.Node)
	}

	// do header file generation
	fmt.Fprintf(w, "// C Header File Generated by Yang Compiler\n")
	tds := yang.TypeDict.Typedefs()
	printTypedefs(w, tds) // look up by nodes?
}

// Print type dictionary (by twkim)
func printTypedefs(w io.Writer, tds []*yang.Typedef) {
	for _, v := range tds {
		// case enumeration
		kind := (*v.YangType).Kind
		fmt.Fprintf(w, "%s %s {\n", kind, v.Name)
		fmt.Fprintf(w, "}\n")
	}
}
